[theme]
# Core color scheme - Professional fintech palette
primaryColor = "#1E40AF"           # Deep blue for CTAs and interactive elements
backgroundColor = "#FFFFFF"         # Pure white background
secondaryBackgroundColor = "#F8FAFC"  # Light gray for cards and secondary areas
textColor = "#0F172A"              # Almost black for maximum contrast

# Typography - Clean, professional system fonts
font = "system-ui"
baseFontSize = 16
baseFontWeight = 400

# Visual refinement for professional appearance
baseRadius = 6                     # Subtle rounded corners

# Professional UI colors
base = "light"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
